name: train_mcd
gpu: True
data_path: &data_path /data/zhangruwen/MM_Controversy_Detection_Released-main/mcd/dataset/ours
baseline_type: mcd
log_type: base_9
seed: 42
batch_size: 256
num_works: 8
epochs: 100
lr: 0.00006
save_threshold: 0.0
epoch_stop: 10
log_freq: 10
alpha: 0.8

data:
  train:
    target: mcd.src.ours_dataset.Oursdataset
    params:
      base_path: *data_path
      path_vid: vid_fold_train.txt
  valid:
    target: mcd.src.ours_dataset.Oursdataset
    params:
      base_path: *data_path
      path_vid: vid_fold_valid.txt
  test:
    target: mcd.src.ours_dataset.Oursdataset
    params:
      base_path: *data_path
      path_vid: vid_fold_test.txt

model:
  smoothness_ratio: 0
  degree_ratio: 0
  sparsity_ratio: 0.3
  v_moe:
    num_feature: 8
    cls_dim: 128
    feature_dim: 768
    feature_hidden_dim: 128
    num_trans_heads: 2
    dropout: 0.1
    moe_in_feature: 128
    moe_hidden_feature: 128
    moe_out_feature: 128
    num_experts: 3
    k: 1
